import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono,
    Inter,
    Roboto,
    Poppins,
    Open_Sans,
    Source_Code_Pro,
    Comfortaa,
    Patrick_Hand,
    Space_Mono,
    Paytone_One,
    Righteous,
    Monoton
} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { ThemeSelector } from "@/components/ThemeSelector";

const geistSans = Geist({
    variable: "--font-geist",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const roboto = Roboto({
    variable: "--font-roboto",
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
});

const openSans = Open_Sans({
    variable: "--font-openSans",
    subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
    variable: "--font-sourceCodePro",
    subsets: ["latin"],
});

const comfortaa = Comfortaa({
    variable: "--font-comfortaa",
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
});

const patrickHand = Patrick_Hand({
    variable: "--font-patrickHand",
    weight: ["400"],
    subsets: ["latin"],
});

const spaceMono = Space_Mono({
    variable: "--font-spaceMono",
    weight: ["400", "700"],
    subsets: ["latin"],
});

const paytoneOne = Paytone_One({
    variable: "--font-paytoneOne",
    weight: ["400"],
    subsets: ["latin"],
});

const righteous = Righteous({
    variable: "--font-righteous",
    weight: ["400"],
    subsets: ["latin"],
});

const monoton = Monoton({
    variable: "--font-monoton",
    weight: ["400"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${roboto.variable} ${poppins.variable} ${openSans.variable} ${sourceCodePro.variable} ${comfortaa.variable} ${patrickHand.variable} ${spaceMono.variable} ${paytoneOne.variable} ${righteous.variable} ${monoton.variable} antialiased`}
            >
                <ThemeProvider>
                    <ThemeSelector />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
